[development]
# Development Secrets
POSTGRES_USER = ""
POSTGRES_PASSWORD = ""

[production]
#  Production Secrets
POSTGRES_USER = ""
POSTGRES_PASSWORD = ""

[staging]
# Staging Secrets
POSTGRES_USER = ""
POSTGRES_PASSWORD = ""
