"""Add better-auth supabase compatibility columns.

Revision ID: 121117e5c0c0
Revises: 07bd10555020
Create Date: 2026-01-04 23:56:29.001320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '121117e5c0c0'
down_revision: Union[str, Sequence[str], None] = '07bd10555020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAnonymous', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('phoneNumber', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('phoneNumberVerified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('userMetadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user', sa.Column('appMetadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user', sa.Column('invitedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('lastSignInAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_user_phoneNumber'), 'user', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phoneNumber'), table_name='user')
    op.drop_column('user', 'lastSignInAt')
    op.drop_column('user', 'invitedAt')
    op.drop_column('user', 'appMetadata')
    op.drop_column('user', 'userMetadata')
    op.drop_column('user', 'phoneNumberVerified')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'isAnonymous')
    # ### end Alembic commands ###
