"""Disable unique invoice number constraint from DB, enforce uniqueness on creation instead.

Revision ID: 19f717325981
Revises: 3a61bfec7750
Create Date: 2026-01-16 15:34:49.017266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '19f717325981'
down_revision: Union[str, Sequence[str], None] = '3a61bfec7750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
