"""Add usage period to the subscription plan.

Revision ID: 2c3511ea15a1
Revises: 8662c3749550
Create Date: 2025-12-08 18:22:47.751041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2c3511ea15a1'
down_revision: Union[str, Sequence[str], None] = '8662c3749550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('usage_period', sqlmodel.sql.sqltypes.AutoString(), server_default='monthly', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_plans', 'usage_period')
    # ### end Alembic commands ###
