"""Add limits active boolean to subscription plan.

Revision ID: 32b2a1a5620e
Revises: 2c3511ea15a1
Create Date: 2025-12-15 13:57:56.678234

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32b2a1a5620e"
down_revision: Union[str, Sequence[str], None] = "2c3511ea15a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subscription_plans",
        sa.Column("limits_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscription_plans", "limits_active")
    # ### end Alembic commands ###
