"""Add additional tax prcentage and type to invoice models.

Revision ID: 3577d2aacfcd
Revises: 8029121f2a3c
Create Date: 2025-12-08 13:06:23.182466

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3577d2aacfcd"
down_revision: Union[str, Sequence[str], None] = "8029121f2a3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column(
            "additional_tax_type",
            sqlmodel.sql.sqltypes.AutoString(),
            server_default="none",
            nullable=False,
        ),
    )
    op.add_column(
        "invoices", sa.Column("additional_tax_percentage", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "additional_tax_percentage")
    op.drop_column("invoices", "additional_tax_type")
    # ### end Alembic commands ###
