"""Update CASCADE constrainst for customer and product references to use Restrict to disallow deletion if referenced.

Revision ID: 35f572a79db2
Revises: 3e8c919e2488
Create Date: 2025-12-29 13:55:47.636582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '35f572a79db2'
down_revision: Union[str, Sequence[str], None] = '3e8c919e2488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoice_items_product_id_fkey'), 'invoice_items', type_='foreignkey')
    op.create_foreign_key(None, 'invoice_items', 'products', ['product_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('invoices_customer_id_fkey'), 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('user_plans_plan_id_fkey'), 'user_plans', type_='foreignkey')
    op.create_foreign_key(None, 'user_plans', 'subscription_plans', ['plan_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_plans', type_='foreignkey')
    op.create_foreign_key(op.f('user_plans_plan_id_fkey'), 'user_plans', 'subscription_plans', ['plan_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key(op.f('invoices_customer_id_fkey'), 'invoices', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.create_foreign_key(op.f('invoice_items_product_id_fkey'), 'invoice_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
