"""Remove better-auth supabase compatibility columns.

Revision ID: 3a61bfec7750
Revises: 121117e5c0c0
Create Date: 2026-01-05 03:52:07.123278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a61bfec7750'
down_revision: Union[str, Sequence[str], None] = '121117e5c0c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phoneNumber'), table_name='user')
    op.drop_column('user', 'phoneNumberVerified')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'userMetadata')
    op.drop_column('user', 'lastSignInAt')
    op.drop_column('user', 'isAnonymous')
    op.drop_column('user', 'invitedAt')
    op.drop_column('user', 'appMetadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('appMetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('invitedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('isAnonymous', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('lastSignInAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('userMetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('phoneNumberVerified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_phoneNumber'), 'user', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###
