"""Fix Model Schemas Timestamps

Revision ID: 5f49527f84cb
Revises: bba517cdac58
Create Date: 2025-09-23 15:19:37.797075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5f49527f84cb'
down_revision: Union[str, Sequence[str], None] = 'bba517cdac58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_apikey_id'), 'apikey', ['id'], unique=False)
    op.create_index(op.f('ix_jwks_id'), 'jwks', ['id'], unique=False)
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_verification_id'), 'verification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_id'), table_name='verification')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_index(op.f('ix_jwks_id'), table_name='jwks')
    op.drop_index(op.f('ix_apikey_id'), table_name='apikey')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    # ### end Alembic commands ###
