"""Add discount percentage and additional tax amount to invoice table.

Revision ID: 8662c3749550
Revises: 45beb3c4507e
Create Date: 2025-12-08 14:10:21.507286

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8662c3749550"
down_revision: Union[str, Sequence[str], None] = "45beb3c4507e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column(
            "discount_percentage", sa.Float(), nullable=False, server_default="0.0"
        ),
    )
    op.add_column(
        "invoices", sa.Column("additional_tax_amount", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "additional_tax_amount")
    op.drop_column("invoices", "discount_percentage")
    # ### end Alembic commands ###
