"""Add UOM to HS Codes

Revision ID: 9b7d97c8a81f
Revises: bb0a6f499675
Create Date: 2025-11-16 15:39:33.594687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9b7d97c8a81f'
down_revision: Union[str, Sequence[str], None] = 'bb0a6f499675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hs_codes', sa.Column('uom', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hs_codes', 'uom')
    # ### end Alembic commands ###
