"""Change Profile/FBRProfile Layout

Revision ID: bba517cdac58
Revises: 988cd82c7606
Create Date: 2025-09-22 00:04:50.312415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'bba517cdac58'
down_revision: Union[str, Sequence[str], None] = '988cd82c7606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fbr_profiles', sa.Column('national_tax_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('fbr_profiles', sa.Column('sales_tax_registration_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('user_profiles', 'national_tax_number')
    op.drop_column('user_profiles', 'logo_url')
    op.drop_column('user_profiles', 'sales_tax_registration_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('sales_tax_registration_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('logo_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('national_tax_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fbr_profiles', 'sales_tax_registration_number')
    op.drop_column('fbr_profiles', 'national_tax_number')
    # ### end Alembic commands ###
