"""Add better-auth anonymous and phone number plugin columns.

Revision ID: c59cd29da7a1
Revises: 19f717325981
Create Date: 2026-01-21 16:05:57.757312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c59cd29da7a1'
down_revision: Union[str, Sequence[str], None] = '19f717325981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isAnonymous', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user', sa.Column('phoneNumber', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('phoneNumberVerified', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_phoneNumber'), 'user', ['phoneNumber'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phoneNumber'), table_name='user')
    op.drop_column('user', 'phoneNumberVerified')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'isAnonymous')
    # ### end Alembic commands ###
