"""Implement auto-renew functionality.

Revision ID: e3259457f50c
Revises: d0af47fcd2f5
Create Date: 2026-02-26 21:09:04.331481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e3259457f50c'
down_revision: Union[str, Sequence[str], None] = 'd0af47fcd2f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('auto_renew', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_plans', 'auto_renew')
    # ### end Alembic commands ###
