"""Enforce unique constraint on hs codes.

Revision ID: e90f1da0227f
Revises: f381dd79b7f2
Create Date: 2025-12-18 18:29:42.021730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e90f1da0227f'
down_revision: Union[str, Sequence[str], None] = 'f381dd79b7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'hs_codes', ['hs_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hs_codes', type_='unique')
    # ### end Alembic commands ###
