"""Add multiple units of measurement for each hs code.

Revision ID: f381dd79b7f2
Revises: f8fe439e1bcc
Create Date: 2025-12-18 18:16:13.337835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f381dd79b7f2'
down_revision: Union[str, Sequence[str], None] = 'f8fe439e1bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hs_codes', sa.Column('units_of_measurement', sa.ARRAY(sa.TEXT()), nullable=False))
    op.drop_column('hs_codes', 'uom')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hs_codes', sa.Column('uom', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hs_codes', 'units_of_measurement')
    # ### end Alembic commands ###
